name: bond-case-study
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - pycountry
  - pip
  - pip:
      - yfinance
      - mplfinance
      - pandas_ta
